### PR TITLE
Fix nonempty_improper_list_of/2 generator

### LINKED ISSUE #169: nonempty_improper_list_of generator (and by extension maybe_improper_list_generator) are incorrect
The generator

```elixir
StreamData.nonempty_improper_list_of(StreamData.integer(), StreamData.boolean())
```
has quite a high chance to generate `[true]` or `[false]`, but it should never do so.
`[true]` and `[false]` are not improper lists, but proper lists (syntactic sugar for `[true | []]` resp `[false | []]`).

I think the case over here:
https://github.com/whatyouhide/stream_data/blob/e8fd3355b38317a235929745663df32904bcf4d7/lib/stream_data.ex#L1100

is incorrect.
StreamData should not generate empty lists (and then this case will never happen).

### PR DESCRIPTION
**Pull request by Qqwy**
Ensures `[terminator]` will not be generated anymore by `nonempty_improper_list_of/2`

Fixes #169

### CODE REVIEW

File: test/stream_data_test.exs [hunk 1]
```diff
@@ -446,12 +446,14 @@ defmodule StreamDataTest do
   property "nonempty_improper_list_of/2" do
     check all list <- nonempty_improper_list_of(integer(), constant("")) do
       assert list != []
+      assert list != [""]
```
Comment (whatyouhide) [inline test/stream_data_test.exs:449]: I think the test you want here to be more precise is

```suggestion
      refute match?([_], list)
```

**Comment by Qqwy** [comment]
The CI run is failing, but not on a test that has to do with this PR it seems.
