### PR TITLE
Fix stacktraces for filters in "gen all"/"check all"

### LINKED ISSUE #46: Investigate proper stacktraces for filters in check all / gen all

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #46.

### CODE REVIEW

File: lib/ex_unit_properties.ex [hunk 1]
```diff
@@ -241,33 +241,52 @@ defmodule ExUnitProperties do
...
               [
                 {unquote(Macro.to_string(clause)), generated_value}
                 | var!(generated_values, unquote(__MODULE__))
               ]
 
-            unquote(compile_clauses(rest, body))
-          _other ->
+            unquote(compile_clauses(rest, body, line))
+
+          other, tries_left = 1 ->
```
Comment (josevalim) [inline lib/ex_unit_properties.ex]: Unused variable (albeit we don't warn for generated code).
